#! /bin/bash

while getopts ":hm:s:" opt; do
  case $opt in
  m)
    HEAP=-Xmx${OPTARG}G
    ;;
  s)
    STACK=-Xss${OPTARG}M
    ;;
  h)
    cat <<EoF
Usage: ${0##*/} [-m max_heap_GB] [-s stack_MB] {tika|ner|search|util} [option]...
EoF
    exit 0
    ;;
  :)
    echo "Option -$OPTARG requires an argument." >&2
    exit -1
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit -2
    ;;
  esac
done

eval cmd=\$$OPTIND
shift $OPTIND
# echo $cmd "$@"

# default for util --email is 2M stack, else JVM default is 1M
[[ -z "$STACK" ]] && [[ "$cmd" == "util" ]] && [[ "$*" == *--email* ]] && STACK="-Xss2M"

getJar() {
  echo ${DFUS_DIR}/dataFusion-${1}/target/scala-${SCALA_VER}/datafusion-${1}_${SCALA_VER}-${DFUS_VER}-one-jar.jar
}

java $HEAP $STACK -jar `getJar $cmd` "$@"
