#! /bin/bash

# error if these vars not set
: ${DFUS_DIR:?must be set to the location of the dataFusion source tree cloned from from https://github.com/data61/dataFusion/. \"source sh/setenv\" from the dataFusion directory to set the environment.}
: ${SCALA_VER:?must be set to the Scala version. \"source sh/setenv\" from the dataFusion directory to set the environment.}
: ${DFUS_VER:?must be set to the dataFusion version. \"source sh/setenv\" from the dataFusion directory to set the environment.}

while getopts ":hm:s:" opt; do
  case $opt in
  m)
    HEAP=-Xmx${OPTARG}G
    ;;
  s)
    STACK=-Xss${OPTARG}M
    ;;
  h)
    cat <<EoF
Usage: ${0##*/} [-m max_heap_GB] [-s stack_MB] {tika|ner|search|util} [option]...
EoF
    exit 0
    ;;
  :)
    echo "Option -$OPTARG requires an argument." >&2
    exit -1
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit -2
    ;;
  esac
done

eval cmd=\$$OPTIND
shift $OPTIND
# echo $cmd "$@"

getJar() {
  echo ${DFUS_DIR}/dataFusion-${1}/target/scala-${SCALA_VER}/datafusion-${1}_${SCALA_VER}-${DFUS_VER}-one-jar.jar
}

java $HEAP $STACK -jar `getJar $cmd` "$@"
