FROM ubuntu:latest 

ENV LANGUAGE=en
ENV LC_ALL=C
ENV LANG=C
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre

# openblas and build tools are to build MITIE (used by dataFusion-ner)
# graphviz is for dependency graphs generated as part of the sbt build
# libreoffice, tesseract and imagemagick are used by dataFusion-tika (and its unit tests)

RUN apt-get update && \
  apt-get install -y gnupg curl unzip libopenblas-dev build-essential gfortran cmake swig git openjdk-8-jdk graphviz libreoffice tesseract-ocr tesseract-ocr-eng imagemagick && \
  update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

RUN echo "deb https://dl.bintray.com/sbt/debian /" > /etc/apt/sources.list.d/sbt.list && \
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
  apt-get update && \
  apt-get install -y sbt

ENTRYPOINT ["bash"]
